/* Juniper Junos Secure Hierarchical Configuration */
system {
    host-name EDGE-SEC-SRX-01;
    domain-name enterprise.net;
    services {
        ssh {
            protocol-version v2;
            connection-limit 5;
        }
        web-management {
            https {
                system-generated-certificate;
                interface ge-0/0/1.0;
            }
        }
    }
    syslog {
        host 10.20.1.50 {
            any info;
            facility-override local0;
        }
    }
}
security {
    policies {
        from-zone trust to-zone untrust {
            policy restricted-web {
                match {
                    source-address any;
                    destination-address any;
                    application junos-https;
                }
                then {
                    permit;
                    log {
                        session-close;
                    }
                }
            }
            policy default-deny {
                match {
                    source-address any;
                    destination-address any;
                    application any;
                }
                then {
                    deny;
                    log {
                        session-init;
                    }
                }
            }
        }
    }
}
