# Juniper Junos Mixed Configuration
set system host-name BRANCH-SRX-03
set system services ssh protocol-version v2
# Insecure HTTP web management still enabled
set system services web-management http interface ge-0/0/1.0

set security policies from-zone trust to-zone untrust policy corporate-traffic match source-address any
set security policies from-zone trust to-zone untrust policy corporate-traffic match destination-address any
set security policies from-zone trust to-zone untrust policy corporate-traffic match application junos-https
set security policies from-zone trust to-zone untrust policy corporate-traffic then permit
# Notice: Missing "then log" statement
