"""add_unresolved_models

Revision ID: a436a13bcca7
Revises: 
Create Date: 2026-09-06 18:06:42.215154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a436a13bcca7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blockchain_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_index', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=True),
    sa.Column('audit_id', sa.Integer(), nullable=True),
    sa.Column('event_data', sa.JSON(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('block_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block_index')
    )
    with op.batch_alter_table('blockchain_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blockchain_blocks_id'), ['id'], unique=False)

    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=100), nullable=False),
    sa.Column('vendor', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_id'), ['id'], unique=False)

    op.create_table('configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('vendor', sa.String(length=50), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=True),
    sa.Column('line_count', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('is_sandbox', sa.Boolean(), nullable=True),
    sa.Column('parent_config_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['parent_config_id'], ['configurations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('configurations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configurations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_configurations_sha256_hash'), ['sha256_hash'], unique=False)

    op.create_table('audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('configuration_id', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('stage', sa.String(length=100), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('findings_count', sa.Integer(), nullable=True),
    sa.Column('compliance_score', sa.Float(), nullable=True),
    sa.Column('is_verification', sa.Boolean(), nullable=True),
    sa.Column('parent_audit_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audits_id'), ['id'], unique=False)

    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('vendor', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('line_numbers', sa.JSON(), nullable=True),
    sa.Column('impact', sa.Text(), nullable=False),
    sa.Column('severity_score', sa.Integer(), nullable=True),
    sa.Column('exposure_score', sa.Integer(), nullable=True),
    sa.Column('impact_score', sa.Integer(), nullable=True),
    sa.Column('exploitability_score', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('remediation_recommendation', sa.Text(), nullable=False),
    sa.Column('remediation_diff', sa.JSON(), nullable=True),
    sa.Column('compliance_mappings', sa.JSON(), nullable=True),
    sa.Column('ai_explanation', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_id'), ['id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_id'), ['id'], unique=False)

    op.create_table('remediations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.String(length=50), nullable=False),
    sa.Column('current_config', sa.Text(), nullable=False),
    sa.Column('recommended_config', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('remediations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remediations_id'), ['id'], unique=False)

    op.create_table('unresolved_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('configuration_id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=True),
    sa.Column('case_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('vendor', sa.String(length=50), nullable=False),
    sa.Column('feature', sa.String(length=100), nullable=True),
    sa.Column('rule_id', sa.String(length=100), nullable=True),
    sa.Column('source_lines', sa.JSON(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('normalized_facts', sa.JSON(), nullable=True),
    sa.Column('missing_reference', sa.JSON(), nullable=True),
    sa.Column('unknown_syntax', sa.JSON(), nullable=True),
    sa.Column('ai_analysis', sa.JSON(), nullable=True),
    sa.Column('ai_analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer', sa.String(length=100), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_context', sa.Text(), nullable=True),
    sa.Column('resolution_evidence', sa.JSON(), nullable=True),
    sa.Column('final_verdict', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unresolved_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unresolved_cases_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index('ix_unresolved_cases_audit_status', ['audit_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_unresolved_cases_configuration_id'), ['configuration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_unresolved_cases_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_unresolved_cases_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_unresolved_cases_status'), ['status'], unique=False)
        batch_op.create_index('ix_unresolved_cases_type', ['case_type'], unique=False)

    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remediation_id', sa.Integer(), nullable=False),
    sa.Column('reviewer', sa.String(length=100), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['remediation_id'], ['remediations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_id'), ['id'], unique=False)

    op.create_table('unresolved_case_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('previous_status', sa.String(length=30), nullable=False),
    sa.Column('new_status', sa.String(length=30), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['unresolved_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unresolved_case_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unresolved_case_history_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_unresolved_case_history_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unresolved_case_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unresolved_case_history_id'))
        batch_op.drop_index(batch_op.f('ix_unresolved_case_history_case_id'))

    op.drop_table('unresolved_case_history')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_id'))

    op.drop_table('approvals')
    with op.batch_alter_table('unresolved_cases', schema=None) as batch_op:
        batch_op.drop_index('ix_unresolved_cases_type')
        batch_op.drop_index(batch_op.f('ix_unresolved_cases_status'))
        batch_op.drop_index(batch_op.f('ix_unresolved_cases_id'))
        batch_op.drop_index(batch_op.f('ix_unresolved_cases_finding_id'))
        batch_op.drop_index(batch_op.f('ix_unresolved_cases_configuration_id'))
        batch_op.drop_index('ix_unresolved_cases_audit_status')
        batch_op.drop_index(batch_op.f('ix_unresolved_cases_audit_id'))

    op.drop_table('unresolved_cases')
    with op.batch_alter_table('remediations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remediations_id'))

    op.drop_table('remediations')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_id'))

    op.drop_table('reports')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_id'))

    op.drop_table('findings')
    with op.batch_alter_table('audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audits_id'))

    op.drop_table('audits')
    with op.batch_alter_table('configurations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configurations_sha256_hash'))
        batch_op.drop_index(batch_op.f('ix_configurations_id'))

    op.drop_table('configurations')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_id'))

    op.drop_table('devices')
    with op.batch_alter_table('blockchain_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blockchain_blocks_id'))

    op.drop_table('blockchain_blocks')
    # ### end Alembic commands ###
